core/urls.py
from django.urls import path

from core import views


app_name = 'core'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
]

series/urls.py
from django.urls import path

from series import views


app_name = 'series'

urlpatterns = [
    path('create_series/', views.create_series, name='create_series'),
    path('list_series/', views.list_series, name='list_series'),
    path('<int:series_id>/delete_series/', views.delete_series, name='delete_series'),
    path('<int:series_id>/update_series', views.update_series, name='update_series'),
]

series_reminder/urls.py
from django.contrib import admin
from django.urls import path, include

import core.urls
import series.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(core.urls, namespace='core')),
    path('series/', include(series.urls, namespace='series')),
]

series/models.py
from django.db import models
from django.contrib.auth.models import User


class SeriesManager(models.Manager):
    
    def get_by_user(self, user):
        """ Returns all series related to a user """
        query_set = super().get_queryset().filter(user_id=user.id)
        return query_set
    
    def get_by_id(self, series_id):
        """ Gets series from id """
        series = super().get_queryset().get(id=series_id)
        return series
    
    def get_by_name(self, name):
        series = super().get_queryset().get(name=name)
        return series


class Series(models.Model):
    
    name = models.CharField(max_length=150)
    episode = models.IntegerField()
    season = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    
    objects = SeriesManager()

    class Meta:
        verbose_name = 'Series'
        verbose_name_plural = 'Series'

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password',
        )

series/forms.py
from django import forms

from series.models import Series


class SeriesForm(forms.ModelForm):
    class Meta:
        model = Series
        fields = ('name', 'episode', 'season')

core/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from series_reminder.funcs import generic_message

from core.forms import UserForm


def register(request):

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            return HttpResponseRedirect(reverse('series:list_series'))

        else:
            print(user_form.errors)
            return generic_message(request, 'Invalid form')

    else:
        user_form = UserForm()

        return render(request, 'core/register.html', context={
            'user_form': user_form,
        })


def user_login(request):

    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('series:list_series'))

            else:
                return generic_message(request, 'Invalid login.')

        else:
            return render(request, 'core/user_login.html', context={})

    else:
        return generic_message(request, 'You already are logged in.')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('core:user_login'))

series/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from series.forms import SeriesForm
from series.models import Series

from series_reminder.funcs import generic_message


@login_required
def create_series(request):

    if request.method == 'POST':
        series_form = SeriesForm(data=request.POST)

        if series_form.is_valid():
            series = series_form.save(commit=False)
            series.user = request.user
            series.save()

            return HttpResponseRedirect(reverse('series:list_series'))

        else:
            return generic_message(request, 'Invalid form')

    else:
        series_form = SeriesForm()
        return render(request, 'series/create_series.html', context={
            'series_form': series_form,
        })


@login_required
def list_series(request):

    user = request.user
    series_list = Series.objects.get_by_user(user).order_by('name')

    return render(request, 'series/list_series.html', context={
        'series_list': series_list,
    })


@login_required
def delete_series(request, series_id):

    series = Series.objects.get_by_id(series_id)

    if series.user == request.user:
        series.delete()
        return HttpResponseRedirect(reverse('series:list_series'))

    else:
        return generic_message(request, 'You are not allowed to do this.')


@login_required
def update_series(request, series_id):

    series = Series.objects.get_by_id(series_id)

    if series.user == request.user:
        if request.method == 'POST':
            series.episode = request.POST.get('episode_input')
            series.season = request.POST.get('season_input')
            series.save()

            return HttpResponseRedirect(reverse('series:list_series'))

        else:
            return generic_message(request, 'Error. Expected POST method.')

    else:
        return generic_message(request, 'You are not allowed to do this.')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Series Reminder</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous">
    </script>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a href="{% if user.is_authenticated %}
                    {% url 'series:list_series' %}
                {% endif %}"
           class="navbar-brand"
        >Series Reminder</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link">Github</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link"><span class="fa fa-user" style="padding-right: 5px;"></span>{{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'core:user_logout' %}"  class="nav-link"><span class="fa fa-sign-out"></span>Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'core:user_login' %}" class="nav-link"><span class="fa fa-sign-in"style="padding-right: 3px;"></span>Log in</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'core:register' %}" class="nav-link"><span class="fa fa-user-plus"style="padding-right: 3px;"></span>Register</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock body_block %}
    </div>
</body>
</html>

templates/core/register.html
{% extends "base.html" %}


{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h2>Thank you for registering</h2><br>
        {% else %}
            <h2>Register here</h2><br>

            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <table class="table">
                    {{ user_form.as_table }}
                </table>
                <br>
                <input type="submit" value="Register" class="btn btn-primary">
            </form>
        {% endif %}
    </div>
{% endblock body_block %}

templates/core/user_login.html
{% extends "base.html" %}


{% block body_block %}
    <div class="jumbotron">
        <h2>Log in</h2><br>

        <form method="POST" action="{% url 'core:user_login' %}">
            {% csrf_token %}

            <p>
                <label for="usernme">Username:</label>
                <input type="text" name="username" placeholder="username">
            </p>
            <p>
                <label for="password">Password:</label>
                <input type="password" name="password">
            </p>
            <input type="submit" value="Login" class="btn btn-primary">
        </form>
    </div>
{% endblock body_block %}

templates/message.html
{% extends "base.html" %}

{% block body_block %}
    <div class="jumbotron">
        <h2>{{ message }}</h2>
    </div>
{% endblock body_block %}

templates/series/create_series.html
{% extends "base.html" %}

{% block body_block %}
    <div class="jumbotron">
        <h2>Add Series</h2>

        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <table class="table">
                {{ series_form.as_table }}
            </table>
            <input type="submit" value="Confirm" class="btn btn-primary">
        </form>
    </div>
{% endblock body_block %}

templates/series/list_series.html
{% extends "base.html" %}

{% block body_block %}
    <div class="jumbotron">
        {% if series_list %}
            <table class="table" style="font-size: 125%;">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Episode</th>
                        <th scope="col">Season</th>
                    </tr>
                </thead>
                <tbody>
                    {% for series in series_list %}
                        <tr>
                            <td class="series_name">{{ series.name }}</td>
                            <form enctype="multipart/form-data" method="POST"
                                  action="{% url 'series:update_series' series_id=series.id %}">
                                {% csrf_token %}
                                <td><input type="number" name="episode_input" name="episode_input" value="{{ series.episode }}"></td>
                                <td><input type="number" name="season_input" name="season_input" value="{{ series.season }}"></td>
                                <td><input type="submit" value="Update" class="btn btn-outline-success"></td>
                            </form>

                            <td><a href="{% url 'series:delete_series' series.id %}"
                                   class="btn btn-outline-danger"
                                   onclick="return confirm('Are you sure you want to delete?')">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
        <a href="{% url 'series:create_series' %}" class="btn btn-primary">Add Series</a>
    </div>
{% endblock body_block %}